# Generated by Django 4.2.27 on 2025-12-25 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('port', models.PositiveIntegerField(default=3306)),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('database_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SqlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sql_text', models.TextField()),
                ('subject', models.CharField(max_length=255, verbose_name='Objet de l’email')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('execute_at', models.DateTimeField(blank=True, null=True)),
                ('is_periodic', models.BooleanField(default=False)),
                ('periodic_type', models.CharField(blank=True, choices=[('daily', 'Chaque jour'), ('weekly', 'Chaque semaine'), ('monthly', 'Chaque mois')], max_length=10, null=True)),
                ('periodic_time', models.TimeField(blank=True, null=True)),
                ('periodic_weekday', models.CharField(blank=True, choices=[('mon', 'Lundi'), ('tue', 'Mardi'), ('wed', 'Mercredi'), ('thu', 'Jeudi'), ('fri', 'Vendredi'), ('sat', 'Samedi'), ('sun', 'Dimanche')], max_length=3, null=True)),
                ('periodic_monthday', models.PositiveIntegerField(blank=True, null=True)),
                ('is_executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='app_rapports.databaseconnection')),
                ('emails', models.ManyToManyField(blank=True, related_name='queries', to='app_rapports.emailcontact')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('execute_at', models.DateTimeField(blank=True, null=True)),
                ('is_periodic', models.BooleanField(default=False)),
                ('periodic_type', models.CharField(blank=True, choices=[('daily', 'Chaque jour'), ('weekly', 'Chaque semaine'), ('monthly', 'Chaque mois')], max_length=10, null=True)),
                ('periodic_time', models.TimeField(blank=True, null=True)),
                ('periodic_weekday', models.CharField(blank=True, choices=[('mon', 'Lundi'), ('tue', 'Mardi'), ('wed', 'Mercredi'), ('thu', 'Jeudi'), ('fri', 'Vendredi'), ('sat', 'Samedi'), ('sun', 'Dimanche')], max_length=3, null=True)),
                ('periodic_monthday', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emails', models.ManyToManyField(related_name='reports', to='app_rapports.emailcontact')),
                ('queries', models.ManyToManyField(related_name='reports', to='app_rapports.sqlquery')),
            ],
        ),
    ]
