# Generated by Django 4.2.27 on 2025-12-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='execute_at',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='is_executed',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='is_periodic',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='message',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='periodic_monthday',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='periodic_time',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='periodic_type',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='periodic_weekday',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='report',
            name='cc_emails',
            field=models.ManyToManyField(blank=True, related_name='reports_cc', to='app_rapports.emailcontact', verbose_name='Copie (CC)'),
        ),
        migrations.AddField(
            model_name='report',
            name='to_emails',
            field=models.ManyToManyField(related_name='reports_to', to='app_rapports.emailcontact', verbose_name='Destinataires'),
        ),
        migrations.AlterField(
            model_name='report',
            name='execute_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date d’exécution'),
        ),
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du rapport'),
        ),
        migrations.AlterField(
            model_name='report',
            name='queries',
            field=models.ManyToManyField(related_name='reports', to='app_rapports.sqlquery', verbose_name='Requêtes SQL'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Objet de l’email'),
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='sql_text',
            field=models.TextField(verbose_name='Requête SQL'),
        ),
    ]
