# Generated by Django 4.2.27 on 2025-12-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0002_remove_report_emails_remove_sqlquery_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlquery',
            name='emails',
            field=models.ManyToManyField(blank=True, to='app_rapports.emailcontact'),
        ),
    ]
