# Generated by Django 4.2.27 on 2025-12-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0003_sqlquery_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution'),
        ),
        migrations.AlterField(
            model_name='report',
            name='to_emails',
            field=models.ManyToManyField(related_name='reports_to', to='app_rapports.emailcontact', verbose_name='Destinataires (TO)'),
        ),
    ]
