# Generated by Django 4.2.27 on 2025-12-30 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0004_report_last_executed_at_alter_report_to_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_rapports.sqlquery')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app_rapports.report')),
            ],
        ),
    ]
