# Generated by Django 4.2.27 on 2025-12-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0005_reportexecutionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlquery',
            name='emails',
        ),
    ]
