# Generated by Django 4.2.27 on 2025-12-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0006_remove_sqlquery_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cc_emails',
            field=models.ManyToManyField(blank=True, related_name='reports_cc', to='app_rapports.emailcontact'),
        ),
        migrations.AlterField(
            model_name='report',
            name='execute_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='queries',
            field=models.ManyToManyField(related_name='reports', to='app_rapports.sqlquery'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='to_emails',
            field=models.ManyToManyField(related_name='reports_to', to='app_rapports.emailcontact'),
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to='app_rapports.sqlquery')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_rapports.report')),
            ],
        ),
    ]
