# Generated by Django 4.2.27 on 2025-12-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0007_alter_report_cc_emails_alter_report_execute_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportexecutionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='reportexecutionlog',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='app_rapports.sqlquery'),
        ),
    ]
