# Generated by Django 4.2.27 on 2026-01-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0008_alter_reportexecutionlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('oracle', 'Oracle'), ('postgres', 'PostgreSQL')], default='mysql', max_length=20),
        ),
    ]
