# Generated by Django 4.2.27 on 2026-01-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0009_databaseconnection_db_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
