# Generated by Django 4.2.27 on 2026-01-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0010_report_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlquery',
            name='params',
            field=models.JSONField(blank=True, help_text='Exemple : {"agence": ["A01","A02"], "date": ["2026-01-01","2026-01-02"]}', null=True),
        ),
    ]
