# Generated by Django 4.2.27 on 2026-01-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0011_sqlquery_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlquery',
            name='params',
        ),
    ]
