# Generated by Django 4.2.27 on 2026-01-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0012_remove_sqlquery_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='database_name',
            field=models.CharField(help_text='MySQL/Postgres: DB name | Oracle: SERVICE_NAME (ex: FREEPDB1)', max_length=200),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='db_type',
            field=models.CharField(choices=[('oracle', 'Oracle'), ('mysql', 'MySQL'), ('postgres', 'PostgreSQL')], default='oracle', max_length=20),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='port',
            field=models.PositiveIntegerField(default=1521),
        ),
        migrations.CreateModel(
            name='ReportQueryParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rapports.sqlquery')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_parameters', to='app_rapports.report')),
            ],
        ),
    ]
