# Generated by Django 4.2.27 on 2026-01-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0013_alter_databaseconnection_database_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reportqueryparameter',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_parameters', to='app_rapports.sqlquery'),
        ),
        migrations.AlterUniqueTogether(
            name='reportqueryparameter',
            unique_together={('report', 'query', 'name')},
        ),
        migrations.DeleteModel(
            name='ReportFile',
        ),
    ]
