# Generated by Django 4.2.27 on 2026-01-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0014_alter_report_code_alter_reportqueryparameter_query_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='cc_emails',
        ),
        migrations.RemoveField(
            model_name='report',
            name='to_emails',
        ),
        migrations.DeleteModel(
            name='EmailContact',
        ),
        migrations.AddField(
            model_name='report',
            name='cc_emails',
            field=models.TextField(blank=True, help_text='Emails séparés par des virgules'),
        ),
        migrations.AddField(
            model_name='report',
            name='to_emails',
            field=models.TextField(blank=True, help_text='Emails séparés par des virgules'),
        ),
    ]
