# Generated by Django 4.2.27 on 2026-01-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0015_remove_report_cc_emails_remove_report_to_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='cc_emails',
        ),
        migrations.RemoveField(
            model_name='report',
            name='to_emails',
        ),
        migrations.AddField(
            model_name='report',
            name='cc_emails',
            field=models.ManyToManyField(blank=True, related_name='reports_cc', to='app_rapports.emailcontact'),
        ),
        migrations.AddField(
            model_name='report',
            name='to_emails',
            field=models.ManyToManyField(related_name='reports_to', to='app_rapports.emailcontact'),
        ),
    ]
