# Generated by Django 4.2.27 on 2026-01-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0016_emailcontact_remove_report_cc_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('to', 'TO'), ('cc', 'CC')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='cc_emails',
        ),
        migrations.RemoveField(
            model_name='report',
            name='to_emails',
        ),
        migrations.DeleteModel(
            name='EmailContact',
        ),
        migrations.AddField(
            model_name='reportemail',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='app_rapports.report'),
        ),
        migrations.AlterUniqueTogether(
            name='reportemail',
            unique_together={('report', 'email', 'email_type')},
        ),
    ]
