# Generated by Django 4.2.27 on 2026-01-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0018_fix_oracle_email_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlquery',
            name='sum_field',
            field=models.CharField(blank=True, help_text='Nom de la colonne à totaliser', max_length=100, null=True),
        ),
    ]
