# Generated by Django 4.2.27 on 2026-01-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0019_sqlquery_sum_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlquery',
            name='sum_field',
        ),
    ]
