# Generated by Django 4.2.27 on 2026-01-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0020_remove_sqlquery_sum_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportQuerySum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(help_text='Nom de la colonne à sommer ', max_length=100)),
                ('label', models.CharField(blank=True, help_text='Libellé affiché ', max_length=200, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sums', to='app_rapports.sqlquery')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_sums', to='app_rapports.report')),
            ],
            options={
                'unique_together': {('report', 'query')},
            },
        ),
    ]
