# Generated by Django 4.2.27 on 2026-01-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0021_reportquerysum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportquerysum',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reportquerysum',
            name='column_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportquerysum',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportquerysum',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rapports.sqlquery'),
        ),
        migrations.AlterField(
            model_name='reportquerysum',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sums', to='app_rapports.report'),
        ),
    ]
