# Generated by Django 4.2.27 on 2026-01-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0022_alter_reportquerysum_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='enable_totals',
            field=models.BooleanField(default=False, verbose_name='Activer les totaux'),
        ),
        migrations.AddField(
            model_name='report',
            name='total_columns',
            field=models.JSONField(blank=True, help_text='Colonnes à sommer (ex: montant, solde, depot)', null=True),
        ),
        migrations.DeleteModel(
            name='ReportQuerySum',
        ),
    ]
