# Generated by Django 4.2.27 on 2026-01-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0023_report_enable_totals_report_total_columns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='enable_totals',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_columns',
        ),
        migrations.AddField(
            model_name='sqlquery',
            name='enable_totals',
            field=models.BooleanField(default=False, verbose_name='Activer les totaux'),
        ),
        migrations.AddField(
            model_name='sqlquery',
            name='total_columns',
            field=models.JSONField(blank=True, null=True, verbose_name='Colonnes à sommer'),
        ),
        migrations.AddField(
            model_name='sqlquery',
            name='total_label',
            field=models.CharField(default='TOTAL', max_length=50, verbose_name='Nom ligne total'),
        ),
    ]
