# Generated by Django 4.2.27 on 2026-01-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rapports', '0024_remove_report_enable_totals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlquery',
            name='enable_totals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='total_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='total_label',
            field=models.CharField(blank=True, default='TOTAL', max_length=200),
        ),
    ]
